name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      - created

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image:
          - spark-delta
          - kyuubi-delta
          # - strimzi-kafka-connect
          # - cricketeerone-kafka-connect
          # - apache-superset
          # - ml-on-fhir
          # - coder-base
    steps:
      - run: |
          echo "Building ${{ matrix.image }}"

  build:
    if: ${{ false }}
    uses: miracum/.github/.github/workflows/standard-build.yaml@c3f13dd53633bed28ff2667e559d74eae791a1a7 # v1.7.1
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
      actions: read
      security-events: write
    strategy:
      matrix:
        image:
          - spark-delta
          - kyuubi-delta
          # - strimzi-kafka-connect
          # - cricketeerone-kafka-connect
          # - apache-superset
          # - ml-on-fhir
          # - coder-base
    with:
      image: ghcr.io/${{ github.repository }}/${{ matrix.image }}
      build-context: images/${{ matrix.image }}
      enable-build-test-layer: false
      enable-upload-test-image: false
      enable-upload-image: false
      enable-trivy-scan: ${{ matrix.image != 'ml-on-fhir' }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    uses: miracum/.github/.github/workflows/standard-lint.yaml@c3f13dd53633bed28ff2667e559d74eae791a1a7 # v1.7.1
    if: ${{ false }}
    permissions:
      contents: read
      pull-requests: write
      issues: write
      security-events: write
      actions: read
    with:
      enable-validate-gradle-wrapper: false
      enable-codeql: false
      enable-verify-base-image-signature: false
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
