name: scheduled

on:
  repository_dispatch: {}
  workflow_dispatch: {}
  schedule:
    - cron: "00 18 * * *"

permissions: read-all

jobs:
  schedule:
    uses: miracum/.github/.github/workflows/standard-schedule.yaml@7c5194974a95673f832be01920169af6b0db3902 # v1.5.5
    permissions:
      contents: read
      issues: write
      security-events: write
    with:
      images: |
        [
          'ghcr.io/${{ github.repository }}/spark-delta:latest',
          'ghcr.io/${{ github.repository }}/strimzi-kafka-connect:latest',
          'ghcr.io/${{ github.repository }}/cricketeerone-kafka-connect:latest'
        ]
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
